[build]
  command   = "npm run build"
  publish   = "out"
[build.environment]
        NPM_FLAGS="--prefix=/dev/null"

[[plugins]]
  package = "./plugins/pnpm-preinstaller"
[[plugins]]
  package = "@netlify/plugin-nextjs"